countries = {
    'Afeganistão':"afghanistan", 
    'Austrália':'australia', 
    'Azerbaijão':'azerbaijan', 
    'Bangladesh':'bangladesh',
    'Canadá':'canada', 
    'Chile':'chile', 
    'China':'china', 
    'Colômbia':'colombia', 
    'Estados Unidos':'united-states', 
    'Europa': 'european-union', 
    'Geórgia':'georgia', 
    'Grécia':'greece', 
    'Guatemala':'guatemala', 
    'Haiti':'haiti', 
    'Holanda':'netherlands', 
    'Indonésia':'indonesia', 
    'Irã':'iran', 
    'Itália':'italy', 
    'Japão':'japan', 
    'Malta':'malta', 
    'Noruega':'norway', 
    'Paquistão':'pakistan', 
    'Peru':'peru', 
    'Portugal':'portugal', 
    'Rússia':'russia', 
    'Síria':'syria', 
    'Tajiquistão':'tajikistan', 
    'Turquia':'turkey-turkiye',
    'Venezuela':'venezuela', 
    'Índia':'india' }

inverse_countries = {v: k for k, v in countries.items()}